version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]

  test:
    build: .
    environment:
      NODE_ENV: test
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "test"]
